ros_distro: humble
ros_domain_id: 0
image_prefix: lekiwi
registry: docker.io/dragomirxyz
base_image: docker.io/dragomirxyz/robocore_humble_arm64
deploy_mode: live
build_dir: build
components_dir: components
compose_file: docker-compose.yml
mount_root: /home/cdr/robocore-builds
hosts:
- name: rpi5
  ip: pi5.local
  user: cdr
  arch: arm64
components:
- name: rosboard
  folder: components/rosboard
  entrypoint: ros2 run rosboard rosboard_node
  ports:
  - 8888:8888
  packages:
  - rosboard
- name: microros
  folder: components/microros
  entrypoint: ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0
  postinstall:
  - ros2 run micro_ros_setup create_agent_ws.sh
  - ros2 run micro_ros_setup build_agent.sh
  devices:
  - /dev/ttyUSB0:/dev/ttyUSB0
  packages:
  - micro_ros_setup
- name: control
  folder: components/control
  entrypoint: ''
  launch_args: ''
  preinstall: []
  postinstall: []
  devices: []
  ports: []
  packages:
  - omnidirectional_controllers
  - lekiwi_ros_hw_interface
