ros_distro: humble
ros_domain_id: 0
image_prefix: lekiwi
registry: docker.io/dragomirxyz
base_image: docker.io/dragomirxyz/robocore_humble_arm64
deploy_mode: live
build_dir: build
components_dir: components
compose_file: docker-compose.yml
mount_root: /home/cdr/robocore-builds
hosts:
- name: rpi5
  ip: pi5.local
  user: cdr
  arch: arm64
components:
- name: rosboard
  folder: components/rosboard
  entrypoint: ''
  launch_args: ''
  preinstall: []
  postinstall: []
  devices: []
  ports: []
  packages:
  - rosboard
- name: microros
  folder: components/microros
  entrypoint: ''
  launch_args: ''
  preinstall: []
  postinstall: []
  devices: []
  ports: []
  packages:
  - micro_ros_setup
